arch:
    max_epochs: 20
checkpoint:
    filepath: 'E:/md_model/kitti/HRLiteNet_test/640_192'
    save_top_k: -1
model:
    name: 'SelfSupModel'
    optimizer:
        name: 'Adam'
        depth:
            lr: 0.0002
        pose:
            lr: 0.0002
    scheduler:
        name: 'StepLR'
        step_size: 14
        gamma: 0.5
    depth_net:
        name: 'HRLiteNet_v2'
        version: '18pt'
    pose_net:
        name: 'PoseResNet'
        version: '18pt'
    params:
        crop: 'garg'
        min_depth: 0.0
        max_depth: 80.0
datasets:
    augmentation:
        image_shape: (192, 640)
    train:
        batch_size: 16
        dataset: ['KITTI']
        path: ['Y:/KITTI_dataset/KITTI_raw']
        split: ['data_splits/eigen_zhou_files.txt']
        depth_type: ['velodyne']
        repeat: [1]
    validation:
        dataset: ['KITTI']
        path: ['Y:/KITTI_dataset/KITTI_raw']
        split: ['data_splits/eigen_val_files.txt',
                'data_splits/eigen_test_files.txt']
        depth_type: ['velodyne']
    test:
        dataset: ['KITTI']
        path: ['Y:/KITTI_dataset/KITTI_raw']
        split: ['data_splits/eigen_test_files.txt']
        depth_type: ['velodyne']
